//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class fact_estatus
{
    public int id_estatus { get; set; }
    public string desc_estatus { get; set; }
}

public partial class fact_genero
{
    public int id_genero { get; set; }
    public string desc_genero { get; set; }
}

public partial class fact_grado_escolar
{
    public int id_grado_escolar { get; set; }
    public string desc_grado_escolar { get; set; }
    public int id_nivel_escolar { get; set; }
}

public partial class fact_licencias
{
    public int id_licencia { get; set; }
    public string desc_licencia { get; set; }
    public string caracteristica_licecia { get; set; }
}

public partial class fact_materia_exam
{
    public int id_materia_exam { get; set; }
    public string desc_materia_exam { get; set; }
    public Nullable<int> id_nivel_exam { get; set; }
}

public partial class fact_nivel_escolar
{
    public int id_nivel_escolar { get; set; }
    public string desc_nivel_escolar { get; set; }
}

public partial class fact_nivel_exam
{
    public int id_nivel_exam { get; set; }
    public string desc_nivel_exam { get; set; }
}

public partial class fact_tipo_centro
{
    public int id_tipo_centro { get; set; }
    public string desc_tipo_centro { get; set; }
}

public partial class fact_tipo_fiscal
{
    public int id_tipo_fiscal { get; set; }
    public string desc_tipo_fiscal { get; set; }
}

public partial class fact_tipo_rfc
{
    public int id_tipo_rfc { get; set; }
    public string desc_tipo_rfc { get; set; }
}

public partial class fact_tipo_usuario
{
    public int id_tipo_usuario { get; set; }
    public string desc_tipo_usuario { get; set; }
}

public partial class inf_alumnos
{
    public System.Guid id_alumno { get; set; }
    public string id_codigo_alumno { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<int> id_genero { get; set; }
    public Nullable<int> id_tipo_usuario { get; set; }
    public string nombres { get; set; }
    public string a_paterno { get; set; }
    public string a_materno { get; set; }
    public string codigo_alumno { get; set; }
    public string clave { get; set; }
    public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public string cp { get; set; }
    public string calle { get; set; }
    public Nullable<int> id_asenta_cpcons { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_centro
{
    public System.Guid id_centro { get; set; }
    public string id_codigo_centro { get; set; }
    public Nullable<int> id_tipo_centro { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public int id_licencia { get; set; }
    public string nombre { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public string cp { get; set; }
    public string calle { get; set; }
    public Nullable<int> id_asenta_cpcons { get; set; }
    public Nullable<System.DateTime> fecha_corte { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
}

public partial class inf_centro_dep
{
    public int id_sucursal_dep { get; set; }
    public Nullable<System.Guid> id_usuario { get; set; }
    public Nullable<System.Guid> id_centro { get; set; }
}

public partial class inf_contacto_fiscal
{
    public System.Guid id_contacto_fiscal { get; set; }
    public string nombres { get; set; }
    public string a_paterno { get; set; }
    public string a_materno { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public Nullable<System.Guid> id_fiscal { get; set; }
}

public partial class inf_empresa
{
    public System.Guid id_empresa { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<int> id_tipo_rfc { get; set; }
    public string rfc { get; set; }
    public string razon_social { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public string cp { get; set; }
    public string calle { get; set; }
    public Nullable<int> id_asenta_cpcons { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
}

public partial class inf_examenes
{
    public System.Guid id_examenes { get; set; }
    public int id_nivel_exam { get; set; }
    public int id_materia_exam { get; set; }
    public Nullable<System.DateTime> hora_inicio { get; set; }
    public Nullable<System.DateTime> hora_fin { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public Nullable<System.Guid> id_usuario { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_examenes_dep
{
    public int id_examenes_desp { get; set; }
    public int id_pregunta_exam { get; set; }
    public int id_respuestas_exam { get; set; }
    public System.Guid id_examenes { get; set; }
}

public partial class inf_fiscal
{
    public System.Guid id_fiscal { get; set; }
    public string id_codigo_fiscal { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<int> id_tipo_fiscal { get; set; }
    public Nullable<int> id_tipo_rfc { get; set; }
    public string rfc { get; set; }
    public string razon_social { get; set; }
    public string telefono { get; set; }
    public string email { get; set; }
    public string cp { get; set; }
    public string calle { get; set; }
    public Nullable<int> id_asenta_cpcons { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_gastos
{
    public System.Guid id_gasto { get; set; }
    public string id_codigo_gasto { get; set; }
    public string categoria { get; set; }
    public string desc_gasto { get; set; }
    public Nullable<int> cantidad { get; set; }
    public Nullable<decimal> costo { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_inventario
{
    public System.Guid id_inventario { get; set; }
    public string id_codigo_inventario { get; set; }
    public Nullable<int> id_grado_escolar { get; set; }
    public string categoria { get; set; }
    public string desc_inventario { get; set; }
    public string caracteristica { get; set; }
    public Nullable<int> cantidad { get; set; }
    public Nullable<int> cantidad_minima { get; set; }
    public Nullable<decimal> costo { get; set; }
    public Nullable<int> margen { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_preguntas_exam
{
    public int id_pregunta_exam { get; set; }
    public string desc_pregunta_exam { get; set; }
    public int id_materia_exam { get; set; }
}

public partial class inf_preguntas_test
{
    public int id_pregunta { get; set; }
    public string desc_pregunta { get; set; }
}

public partial class inf_respuestas_exam
{
    public int id_respuestas_exam { get; set; }
    public string desc_respuestas_exam { get; set; }
    public Nullable<bool> valor_respuesta_exam { get; set; }
    public int id_pregunta_exam { get; set; }
}

public partial class inf_respuestas_test
{
    public int id_respuestas_test { get; set; }
    public string desc_respuestas_test { get; set; }
    public Nullable<bool> valor_respuesta_test { get; set; }
    public int id_pregunta { get; set; }
}

public partial class inf_sepomex
{
    public int id_codigo { get; set; }
    public string d_codigo { get; set; }
    public string d_asenta { get; set; }
    public string d_tipo_asenta { get; set; }
    public string D_mnpio { get; set; }
    public string d_estado { get; set; }
    public string d_ciudad { get; set; }
    public string d_CP { get; set; }
    public string c_estado { get; set; }
    public string c_oficina { get; set; }
    public string c_CP { get; set; }
    public string c_tipo_asenta { get; set; }
    public string c_mnpio { get; set; }
    public Nullable<int> id_asenta_cpcons { get; set; }
    public string d_zona { get; set; }
    public string c_cve_ciudad { get; set; }
}

public partial class inf_test_unam
{
    public System.Guid id_test_unam { get; set; }
    public Nullable<System.Guid> id_usuario { get; set; }
    public string nombre_completo { get; set; }
    public string email { get; set; }
    public Nullable<System.DateTime> hora_inicio { get; set; }
    public Nullable<System.DateTime> hora_fin { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
}

public partial class inf_test_unam_dep
{
    public int id_test_unam_dep { get; set; }
    public int id_pregunta { get; set; }
    public int id_respuestas_test { get; set; }
    public Nullable<System.Guid> id_usuario { get; set; }
}

public partial class inf_usuarios
{
    public System.Guid id_usuario { get; set; }
    public string id_codigo_usuario { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public Nullable<int> id_genero { get; set; }
    public Nullable<int> id_tipo_usuario { get; set; }
    public string nombres { get; set; }
    public string a_paterno { get; set; }
    public string a_materno { get; set; }
    public string codigo_usuario { get; set; }
    public string clave { get; set; }
    public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public Nullable<System.Guid> id_centro { get; set; }
}

public partial class inf_ventas
{
    public System.Guid id_ventas { get; set; }
    public Nullable<int> id_estatus { get; set; }
    public string codigo_venta { get; set; }
    public Nullable<int> tipo_venta { get; set; }
    public Nullable<System.DateTime> fecha_registro { get; set; }
    public System.Guid id_usuario { get; set; }
    public System.Guid id_alumno { get; set; }
    public System.Guid id_centro { get; set; }
}

public partial class inf_ventas_dep
{
    public int id_ventas_dep { get; set; }
    public Nullable<System.Guid> id_inventario { get; set; }
    public Nullable<int> cantidad { get; set; }
    public Nullable<decimal> costo { get; set; }
    public Nullable<System.Guid> id_ventas { get; set; }
}
